# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-23 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180423_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(db_index=True, max_length=256, verbose_name='\u7f51\u5740'),
        ),
    ]
