# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-23 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criticism',
            fields=[
                ('criticismID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('criticismContent', models.TextField()),
                ('criticismTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeID', models.IntegerField(primary_key=True, serialize=False)),
                ('employeeName', models.CharField(max_length=256)),
                ('employeeSex', models.CharField(max_length=10)),
                ('employeeBirth', models.DateField()),
                ('employeePhone', models.CharField(max_length=100)),
                ('employeePlace', models.TextField()),
                ('joinTime', models.DateField()),
                ('password', models.CharField(max_length=256)),
                ('isLead', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('messageTitle', models.CharField(max_length=256)),
                ('messageContent', models.TextField()),
                ('publishTime', models.DateTimeField()),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailySystem.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('replyID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('replyContent', models.TextField()),
                ('replyTime', models.DateTimeField()),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailySystem.Employee')),
                ('messageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailySystem.Message')),
            ],
        ),
        migrations.AddField(
            model_name='criticism',
            name='employeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailySystem.Employee'),
        ),
        migrations.AddField(
            model_name='criticism',
            name='messageID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailySystem.Message'),
        ),
    ]
