# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-23 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailySystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='isLead',
            field=models.BooleanField(default=False),
        ),
    ]
