# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-23 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailySystem', '0002_auto_20180423_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
