# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-25 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailySystem', '0003_auto_20180423_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='employeeID',
            new_name='employee',
        ),
    ]
