# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-25 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailySystem', '0005_auto_20180425_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='employeeName',
            new_name='employee',
        ),
    ]
