# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 10:40
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailySystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messageContent',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u5185\u5bb9'),
        ),
    ]
